### ISSUE TITLE
Overflow faillure

### ISSUE THREAD

**Issue by cornerman57** [Calamari-OCR/calamari#112]
I want to train several models old letter. So I used the N-fold commandline

calamari-cross-fold-train --max_parallel_models=2 --temporary_dir=crosstrainen --files voetius200/????/*.png --best_models_dir bestmodelcross --early_stopping_nbest=5 --n_augmentation=3 --n_folds=2 --weights I:\BIQE\CALAMARI\calamari_models-master\calamari_models-master\antiqua_historical\4.ckpt I:\BIQE\CALAMARI\calamari_models-master\calamari_models-master\antiqua_modern\4.ckpt**

AND
I get the error you see beneath: OverflowError: timeout value is too large
Can anybody tell me what I am doing wrong?

(calamaridev) I:\BIQE\CALAMARI\projects\voetius\TRAINING>calamari-cross-fold-train --max_parallel_models=2 --temporary_dir=crosstrainen --files voetius200/????/*.png --best_models_dir bestmodelcross --early_stopping_nbest=5 --n_augmentation=3 --n_folds=2 --weights I:\BIQE\CALAMARI\calamari_models-master\calamari_models-master\antiqua_historical\4.ckpt I:\BIQE\CALAMARI\calamari_models-master\calamari_models-master\antiqua_modern\4.ckpt
Resolving input files
Found 5842 files in the dataset
Traceback (most recent call last):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\drsjh\Anaconda3\envs\calamaridev\Scripts\calamari-cross-fold-train.exe\__main__.py", line 9, in <module>
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\scripts\cross_fold_train.py", line 80, in main
    temporary_dir=args.temporary_dir, keep_temporary_files=args.keep_temporary_files,
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\ocr\cross_fold_trainer.py", line 149, in run
    pool.map_async(train_individual_model, run_args).get(999999999)
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 651, in get
    self.wait(timeout)
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 648, in wait
    self._event.wait(timeout)
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large

**Comment by ChWick** [comment]
This was a windows specific error that was fixed with c04a98399c95829bc850c85ef4c27c624f8def8d. Please checkout the current master.

If there are further errors, feel free to open new issues!
