### ISSUE TITLE
Error with calamari-cross-fold

### ISSUE THREAD

**Issue by cornerman57** [Calamari-OCR/calamari#113]
I got an error with this script

SCRIPT
calamari-cross-fold-train --max_parallel_models=2 --temporary_dir=crosstrainen --files voetius200/????/*.png --best_models_dir bestmodelcross --early_stopping_nbest=5 --n_augmentation=3 --n_folds=3 --weights I:\BIQE\CALAMARI\projects\voetius\TRAINING\bestmodel\best.ckpt I:\BIQE\CALAMARI\calamari_models-master\calamari_models-master\antiqua_historical\4.ckpt I:\BIQE\CALAMARI\calamari_models-master\calamari_models-master\antiqua_modern\4.ckpt

ERROR
FOLD 2 | Successfully upgraded checkpoint version to 1
FOLD 2 | Codec changes: 14 deletions, 120 appends
Traceback (most recent call last):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\scripts\train.py", line 376, in <module>
    main()
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\scripts\train.py", line 372, in main
    run(args)
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\scripts\train.py", line 364, in run
    progress_bar=not args.no_progress_bars
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\ocr\trainer.py", line 179, in train
    print("CODEC: {}".format(codec.charset))
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0119' in position 478: character maps to <undefined>
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\ocr\cross_fold_trainer.py", line 27, in train_individual_model
    ], args.get("run", None), {"threads": args.get('num_threads', -1)}), verbose=args.get("verbose", False)):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\utils\multiprocessing.py", line 85, in run
    raise Exception("Error: Process finished with code {}".format(process.returncode))
Exception: Error: Process finished with code 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\drsjh\Anaconda3\envs\calamaridev\Scripts\calamari-cross-fold-train.exe\__main__.py", line 9, in <module>
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\scripts\cross_fold_train.py", line 80, in main
    temporary_dir=args.temporary_dir, keep_temporary_files=args.keep_temporary_files,
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\ocr\cross_fold_trainer.py", line 151, in run
    pool.map_async(train_individual_model, run_args).get()
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
Exception: Error: Process finished with code 1

**Comment by cornerman57** [comment]
Can it be an unicode problem?

**Comment by ChWick** [comment]
@cornerman57 this must be some kind of encoding problem with the windows (power)shell, which is not using uft-8 as default. Strange enough the default training runs, but the cross-fold-training which launches new tasks wont run. I'll give it a shot tomorrow, hopefully i'll find a solution...
