### ISSUE TITLE
'context manager not found' while training

### ISSUE THREAD

**Issue by mikegerber** [Calamari-OCR/calamari#116]
I'm testing Calamari using part of the DTA19 training set and I get this error:

~~~sh
calamari-train \
  --files /srv/data/clemens/GT4HistOCR/corpus/dta19/'1832*/*.png' \
  --validation /srv/data/clemens/GT4HistOCR/corpus/dta19/'1804*/*.png' --early_stopping_nbest 10 \
  | tee calamari-train-dta19.log
~~~

~~~
% sh calamari-train-dta19.sh
Resolving input files
Found 9775 files in the dataset
Resolving validation files
Found 5332 files in the validation dataset
Preloading data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9775/9775 [00:30<00:00, 320.04it/s]
Preloading data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 5332/5332 [00:18<00:00, 283.36it/s]
Traceback (most recent call last):
  File "/home/mike/.virtualenvs/calamari/bin/calamari-train", line 11, in <module>
self.dataset = <calamari_ocr.ocr.datasets.input_dataset.StreamingInputDataset object at 0x7f1a488574a8>
Preloading dataset type DataSetMode.TRAIN with size 9775
cm = <calamari_ocr.ocr.datasets.input_dataset.StreamingInputDataset object at 0x7f1a488574a8>
callbacks = deque([(True, <function _BaseExitStack._create_exit_wrapper.<locals>._exit_wrapper at 0x7f1a488168c8>), (True, <function _BaseExitStack._create_exit_wrapper.<locals>._exit_wrapper at 0x7f1a6ce9b840>)])
cb = (True, <function _BaseExitStack._create_exit_wrapper.<locals>._exit_wrapper at 0x7f1a488168c8>)
c.__self__ = <calamari_ocr.ocr.datasets.input_dataset.StreamingInputDataset object at 0x7f1a488574a8>
cb = (True, <function _BaseExitStack._create_exit_wrapper.<locals>._exit_wrapper at 0x7f1a6ce9b840>)
c.__self__ = <calamari_ocr.ocr.datasets.input_dataset.StreamingInputDataset object at 0x7f1a4885eba8>
found = <function _BaseExitStack._create_exit_wrapper.<locals>._exit_wrapper at 0x7f1a488168c8>
self.validation_dataset = <calamari_ocr.ocr.datasets.input_dataset.StreamingInputDataset object at 0x7f1a4885eba8>
Preloading dataset type DataSetMode.TRAIN with size 5332
cm = <calamari_ocr.ocr.datasets.input_dataset.StreamingInputDataset object at 0x7f1a4885eba8>
callbacks = deque([(True, <function _BaseExitStack._create_exit_wrapper.<locals>._exit_wrapper at 0x7f1a487d9d08>)])
cb = (True, <function _BaseExitStack._create_exit_wrapper.<locals>._exit_wrapper at 0x7f1a487d9d08>)
c.__self__ = <calamari_ocr.ocr.datasets.input_dataset.RawInputDataset object at 0x7f1a6cea1978>
found = None
    load_entry_point('calamari-ocr', 'console_scripts', 'calamari-train')()
  File "/home/mike/devel/calamari/calamari_ocr/scripts/train.py", line 372, in main
    run(args)
  File "/home/mike/devel/calamari/calamari_ocr/scripts/train.py", line 364, in run
    progress_bar=not args.no_progress_bars
  File "/home/mike/devel/calamari/calamari_ocr/ocr/trainer.py", line 136, in train
    exit_stack.pop(self.validation_dataset)
  File "/home/mike/devel/calamari/calamari_ocr/utils/contextmanager.py", line 33, in pop
    raise KeyError("context manager not found")
KeyError: 'context manager not found'
~~~

I've included the output from some debugging `print()`s. I'm using Python 3.7.

Any idea what this issue could be?

**Comment by mikegerber** [comment]
I'm on the current master: 

6fd9b2f (HEAD -> master, origin/master, origin/HEAD) Fixed ExitStackWithPop for newer python versions

**Comment by ChWick** [comment]
Thanks for fixing the fix that was no fix!
