### ISSUE TITLE
AttributeError: 'tuple' object has no attribute '__self__'

### ISSUE THREAD

**Issue by xiaoyudannew** [Calamari-OCR/calamari#118]
while execute calamari-train script, it throws this error:

Traceback (most recent call last):
  File "d:\anaconda3\envs\calamari_ocr\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\calamari_ocr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\calamari_ocr\Scripts\calamari-train.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\envs\calamari_ocr\lib\site-packages\calamari_ocr\scripts\train.py", line 372, in main
    run(args)
  File "d:\anaconda3\envs\calamari_ocr\lib\site-packages\calamari_ocr\scripts\train.py", line 364, in run
    progress_bar=not args.no_progress_bars
  File "d:\anaconda3\envs\calamari_ocr\lib\site-packages\calamari_ocr\ocr\trainer.py", line 127, in train
    exit_stack.pop(self.dataset)
  File "d:\anaconda3\envs\calamari_ocr\lib\site-packages\calamari_ocr\utils\contextmanager.py", line 11, in pop
    if cb.__self__ == cm:
AttributeError: 'tuple' object has no attribute '__self__'

**Comment by ChWick** [comment]
See #116 and #117. Should be fixed with the current version (0.3.5)
