### ISSUE TITLE
Using Calamari-OCR to predict multilines images.

### ISSUE THREAD

**Issue by rsierrap** [Calamari-OCR/calamari#119]
Hi, I would like using Calamari-OCR software to predict images in which multiples text lines appear.
So, I try to train from previous checkpoint using images that belong to this kind of image, but this error appears:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had NaN values
	 [[{{node VerifyFinite/CheckNumerics}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py", line 376, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py", line 372, in main
    run(args)
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py", line 364, in run
    progress_bar=not args.no_progress_bars
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/trainer.py", line 183, in train
    self._run_train(train_net, test_net, codec, train_start_time, progress_bar)
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/trainer.py", line 288, in _run_train
    result = train_net.train_step()
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/backends/model_interface.py", line 80, in train_step
    return self.train()
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py", line 505, in train
    cost, probs, seq_len, ler, decoded, gt = self.train_dataset()
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py", line 458, in train_dataset
    self.dropout_rate: self.network_proto.dropout,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had NaN values
	 [[node VerifyFinite/CheckNumerics (defined at /usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py:329) ]]

Caused by op 'VerifyFinite/CheckNumerics', defined at:
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py", line 376, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py", line 372, in main
    run(args)
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py", line 364, in run
    progress_bar=not args.no_progress_bars
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/trainer.py", line 173, in train
    train_net = backend.create_net(self.dataset, codec, restore=None, weights=self.weights, graph_type="train", batch_size=checkpoint_params.batch_size)
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_backend.py", line 30, in create_net
    processes=self.processes,
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py", line 41, in __init__
    self.train_op, self.loss, self.cer = self.create_solver(self.targets, self.time_major_logits, self.logits, self.output_seq_len, self.decoded)
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py", line 329, in create_solver
    clip_norm=tf.minimum(l2_ema / max_l2 * max_grads, max_grads))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/clip_ops.py", line 271, in clip_by_global_norm
    "Found Inf or NaN global norm.")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/numerics.py", line 44, in verify_tensor_all_finite
    return verify_tensor_all_finite_v2(t, msg, name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/numerics.py", line 62, in verify_tensor_all_finite_v2
    verify_input = array_ops.check_numerics(x, message=message)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 919, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had NaN values
	 [[node VerifyFinite/CheckNumerics (defined at /usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py:329) ]]

Executing: python3 -u /usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py --files /tmp/calamariswbp73yk/fold_1.json
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/cross_fold_trainer.py", line 26, in train_individual_model
    ], args.get("run", None), {"threads": args.get('num_threads', -1)}), verbose=args.get("verbose", False)):
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/utils/multiprocessing.py", line 85, in run
    raise Exception("Error: Process finished with code {}".format(process.returncode))
Exception: Error: Process finished with code 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/calamari-cross-fold-train", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/cross_fold_train.py", line 80, in main
    temporary_dir=args.temporary_dir, keep_temporary_files=args.keep_temporary_files,
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/ocr/cross_fold_trainer.py", line 150, in run
    pool.map_async(train_individual_model, run_args).get(999999999)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
Exception: Error: Process finished with code 1
raulsp97@RaulSierraPajares:~$ Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py", line 376, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py", line 372, in main
    run(args)
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py", line 251, in run
    dataset = create_train_dataset(args, dataset_args)
  File "/usr/local/lib/python3.5/dist-packages/calamari_ocr/scripts/train.py", line 174, in create_train_dataset
    print("Resolving input files")
BrokenPipeError: [Errno 32] Broken pipe

Does it have a solution? Is Calamari-OCR compatible with multiple text lines detection? Are you working in this possibility?

Thanks!

**Comment by ChWick** [comment]
Calamari is designed to act on **single text** lines only. Possibly, the crash occurs because you try to train on "invalid" files. You need to split your file into individual files each containing a single line first (Use e.g. ocropus gpage-seg script)
