### ISSUE TITLE
TypeError: ["'", 'e', ':', '?'] has type list, but expected one of: bytes, unicode

### ISSUE THREAD

**Issue by alexander-winkler** [Calamari-OCR/calamari#120]
Hello! I'm using calamari from within the new OCR4all tool under Linux Mint 19.1 Tessa. The OCR process stops with the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/calamari-predict", line 11, in 
    load_entry_point('calamari-ocr==0.3.1', 'console_scripts', 'calamari-predict')()
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-0.3.1-py3.6.egg/calamari_ocr/scripts/predict.py", line 151, in main
    run(args)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-0.3.1-py3.6.egg/calamari_ocr/scripts/predict.py", line 74, in run
    prediction = voter.vote_prediction_result(result)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-0.3.1-py3.6.egg/calamari_ocr/ocr/voting/voter.py", line 19, in vote_prediction_result
    return self.vote_prediction_result_tuple(tuple(prediction_results))
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-0.3.1-py3.6.egg/calamari_ocr/ocr/voting/voter.py", line 45, in vote_prediction_result_tuple
    p.sentence = [c for c, _ in sv.process_text(sentences)]
TypeError: ["'", 'e', ':', '?'] has type list, but expected one of: bytes, unicode
```

What can I do in order to avoid the TypeError?

Many thanks!

**Comment by ChWick** [comment]
You should possibly post this as an issue at https://github.com/OCR4all/OCR4all since it is OCR4all related.

To test if this is a Calamari problem, that also occurs with the current stable version I need
* the model and
* the full calamari-predict all
* exact version of calamari (0.3.1 as far as I see)
