### ISSUE TITLE
pop from empty list [Predicting page-xml]

### ISSUE THREAD

**Issue by deepseek** [Calamari-OCR/calamari#152]
@ChWick @chreul 

When trying to predict an image using page-xml, i am getting an error.
Note that this page-xml file was converted from an alto file using [prima-page-converter](https://github.com/PRImA-Research-Lab/prima-page-converter).

Attached the [model and image.zip](https://github.com/Calamari-OCR/calamari/files/4217311/model.and.image.zip)
```
(calamari) home@home-desktop:~/p13/calamari-master$ calamari-predict --files ./in/img_13. --dataset PAGEXML --checkpoint ./model_00006000.ckpt.json 
img_13.jpg  img_13.xml  
(calamari) home@home-desktop:~/p13/calamari-master$ calamari-predict --files ./in/*.jpg --dataset PAGEXML --checkpoint ./model_00006000.ckpt.json 
Traceback (most recent call last):
  File "/home/home/anaconda3/envs/calamari/bin/calamari-predict", line 8, in <module>
    sys.exit(main())
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/site-packages/calamari_ocr/scripts/predict.py", line 193, in main
    run(args)
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/site-packages/calamari_ocr/scripts/predict.py", line 83, in run
    'pad': args.dataset_pad,
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/dataset_factory.py", line 60, in create_dataset
    args=args)
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/pagexml_dataset/dataset.py", line 219, in __init__
    for sample in loader.load(img, xml):
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/pagexml_dataset/dataset.py", line 156, in _samples_from_book
    "rtype": l.xpath('../@type', namespaces=ns).pop(),
IndexError: pop from empty list
```

**Comment by ChWick** [comment]
Thanks for the report, should be fixed now with 437a77b749dc79feb37fc1c17762f41ca490a02f.
The problem was, that there was no type for the text region, which is however ignored anyway.
