### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: input_data_params:0 is both fed and fetched.

### ISSUE THREAD

**Issue by WeiHin** [Calamari-OCR/calamari#154]
When i run the following command:

calamari-predict --checkpoint "D:\OCR\Calamari OCR\calamari_models-1.0\antiqua_modern\*.ckpt.json" --files "D:\OCR\Calamari OCR\calamari-master\calamari_ocr\test\data\uw3_50lines\test\010001.bin.png"

i have the error as below:

Total params: 1,530,948
Trainable params: 1,530,948
Non-trainable params: 0
__________________________________________________________________________________________________
None
Prediction:   0%|                                                                                | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "c:\users\whkok\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\whkok\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\whkok\Python36\Scripts\calamari-predict.exe\__main__.py", line 9, in <module>
  File "c:\users\whkok\python36\lib\site-packages\calamari_ocr\scripts\predict.py", line 193, in main
    run(args)
  File "c:\users\whkok\python36\lib\site-packages\calamari_ocr\scripts\predict.py", line 102, in run
    for result, sample in do_prediction:
  File "c:\users\whkok\python36\lib\site-packages\calamari_ocr\ocr\predictor.py", line 279, in predict_dataset
    for result, sample in zip(prediction, samples):
  File "c:\users\whkok\python36\lib\site-packages\calamari_ocr\ocr\predictor.py", line 250, in predict_raw
    for result in zip(*prediction):
  File "c:\users\whkok\python36\lib\site-packages\calamari_ocr\ocr\predictor.py", line 166, in predict_raw
    for p, ip in zip(self.network.predict_raw(input_images), input_params):
  File "c:\users\whkok\python36\lib\site-packages\calamari_ocr\ocr\backends\model_interface.py", line 62, in predict_raw
    for r in self.predict_raw_batch(*self.zero_padding(x)):
  File "c:\users\whkok\python36\lib\site-packages\calamari_ocr\ocr\backends\tensorflow_backend\tensorflow_model.py", line 338, in predict_raw_batch
    [x / 255, len_x, np.zeros((len(x), 1), dtype=np.str)],
  File "C:\Users\whkok\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\keras\engine\training.py", line 1156, in predict_on_batch
    outputs = self.predict_function(inputs)
  File "C:\Users\whkok\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\keras\backend.py", line 3473, in __call__
    self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
  File "C:\Users\whkok\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\keras\backend.py", line 3410, in _make_callable
    callable_fn = session._make_callable_from_options(callable_opts)
  File "C:\Users\whkok\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\client\session.py", line 1505, in _make_callable_from_options
    return BaseSession._Callable(self, callable_options)
  File "C:\Users\whkok\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\client\session.py", line 1460, in __init__
    session._session, options_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: input_data_params:0 is both fed and fetched.

Is my command have problem?

**Comment by ChWick** [comment]
Which Tensorflow version are you using? TF >= 2.0 is required.

**Comment by WeiHin** [comment]
![image](https://user-images.githubusercontent.com/61271158/74920897-d992c400-5407-11ea-9bfe-d99cb3eec5e8.png)



 i will try upgrade to TF2.0. thanks

**Comment by ChWick** [comment]
Any updates? Please close this issue if this solved the crash.

**Comment by WeiHin** [comment]
Solved
