### ISSUE TITLE
Some problems with TensorFlow 2.2.0

### ISSUE THREAD

**Issue by poke1024** [Calamari-OCR/calamari#173]
Just tried out TensorFlow 2.2.0. Opening this PR is to track some problems.

Training currently seems to fail:

```
Traceback (most recent call last):
  File "/home/sc.uni-leipzig.de/bo140rasi/.local/bin/calamari-train", line 10, in <module>
    sys.exit(main())
  File "/home/sc.uni-leipzig.de/bo140rasi/.local/lib/python3.7/site-packages/calamari_ocr/scripts/train.py", line 367, in main
    run(args)
  File "/home/sc.uni-leipzig.de/bo140rasi/.local/lib/python3.7/site-packages/calamari_ocr/scripts/train.py", line 359, in run
    progress_bar=not args.no_progress_bars
  File "/home/sc.uni-leipzig.de/bo140rasi/.local/lib/python3.7/site-packages/calamari_ocr/ocr/trainer.py", line 197, in train
    self._run_train(train_net, train_start_time, progress_bar, self.dataset, self.validation_dataset, training_callback)
  File "/home/sc.uni-leipzig.de/bo140rasi/.local/lib/python3.7/site-packages/calamari_ocr/ocr/trainer.py", line 213, in _run_train
    train_net.train(train_dataset, val_dataset, checkpoint_params, self.txt_postproc, progress_bar, training_callback)
  File "/home/sc.uni-leipzig.de/bo140rasi/.local/lib/python3.7/site-packages/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py", line 345, in train
    v_cb, es_cb
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:533 train_step  **
        y, y_pred, sample_weight, regularization_losses=self.losses)
    /nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:183 __call__
        y_true = self._conform_to_outputs(y_pred, y_true)
    /nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:63 _conform_to_outputs
        struct = map_to_output_names(outputs, self._output_names, struct)
    /nfs/cluster/easybuild/software/TensorFlow/2.2.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:587 map_to_output_names
        struct.keys(), output_names))

    ValueError: Found unexpected keys that do not correspond to any Model output: dict_keys(['cer_acc']). Expected: ['ctc']
```

Prediction works, but outputs the same warning message for each predicted line:

```
WARNING:tensorflow:10 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x2b3936e3f200> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.
```

If I find time, I will look into this in more detail.

**Comment by andbue** [comment]
Hi Bernhard, I found this one some weeks ago, it should be fixed with https://github.com/Calamari-OCR/calamari/commit/b9d70315aa8debf0a19d31fa265a2808b39ddc92 – are you on v1.0.5?

**Comment by poke1024** [comment]
I have to admit I just found out I'm still on v1.0.4 :see_no_evil: 

b9d70315aa8debf0a19d31fa265a2808b39ddc92 looks like the perfect fix.

Closing this.
