### ISSUE TITLE
Running the tests

### ISSUE THREAD

**Issue by mikegerber** [Calamari-OCR/calamari#180]
How do I run the tests? Simply setting up a virtualenv, installing the dependencies and Calamari itself (`pip install -e .`) does not seem to be enough and the tests seem to be broken:

~~~
% python test_prediction.py
EEEEE
======================================================================
ERROR: test_prediction (__main__.TestValidationTrain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_prediction.py", line 37, in test_prediction
    run(args)
  File "/home/mike/devel/calamari/calamari_ocr/scripts/predict.py", line 61, in run
    ctc_decoder_params = create_ctc_decoder_params(args)
  File "/home/mike/devel/calamari/calamari_ocr/scripts/predict.py", line 18, in create_ctc_decoder_params
    params.beam_width = args.beam_width
AttributeError: 'PredictionAttrs' object has no attribute 'beam_width'

[ ... more errors ... ]
~~~

**Comment by ChWick** [comment]
This is an old issue, anyways, some updates since tests are crucial:

The testing suite of calamari 2.x was fully reworked. Feel free to open a new isse if there are futher errors.

**Comment by mikegerber** [comment]
This works now, in a virtualenv:
~~~
pip install -r requirements.txt
pip install -e .
pytest
~~~

(I didn't run the complete test suite, though.)
