### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by LauraLittt** [Calamari-OCR/calamari#205]
I tried to use calamari pretrained model, gt4histocr\0.ckpt.

I created my conda environment, ran

pip install calamari_ocr
python setup.py install

I was in my directory containing the calamari model and image and ran the code :
calamari-predict --checkpoint calamari_models\gt4histocr\0.ckpt --files Logos\logo.png

However i faced this error:

Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\Logo\Scripts\calamari-predict-script.py", line 33, in <module>
    sys.exit(load_entry_point('calamari-ocr==2.0.0', 'console_scripts', 'calamari-predict')())
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\calamari_ocr\scripts\predict.py", line 197, in main
    run(args)
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\calamari_ocr\scripts\predict.py", line 98, in run
    predictor = MultiPredictor.from_paths(checkpoints=args.checkpoint, voter_params=voter_params, predictor_params=PredictorParams(silent=True, progress_bar=not args.no_progress_bars))
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\calamari_ocr\ocr\predict\predictor.py", line 48, in from_paths
    checkpoints = [SavedCalamariModel(ckpt, auto_update=auto_update_checkpoints) for ckpt in checkpoints]
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\calamari_ocr\ocr\predict\predictor.py", line 48, in <listcomp>
    checkpoints = [SavedCalamariModel(ckpt, auto_update=auto_update_checkpoints) for ckpt in checkpoints]
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\calamari_ocr\ocr\savedmodel\saved_model.py", line 29, in __init__
    self.update_checkpoint()
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\calamari_ocr\ocr\savedmodel\saved_model.py", line 50, in update_checkpoint
    self._single_upgrade()
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\calamari_ocr\ocr\savedmodel\saved_model.py", line 69, in _single_upgrade
    update_model(self.dict, self.ckpt_path)
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\calamari_ocr\ocr\savedmodel\migrations\version2to3.py", line 19, in update_model
    trainer_params = Scenario.trainer_params_from_dict(params)
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\tfaip\base\scenario\scenariobase.py", line 162, in trainer_params_from_dict
    scenario_params = cls.params_from_dict(d['scenario_params'])
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\tfaip\base\scenario\scenariobase.py", line 117, in params_from_dict
    params: ScenarioBaseParams = cls.get_params_cls().from_dict(d)
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\dataclasses_json\api.py", line 83, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\dataclasses_json\core.py", line 144, in _decode_dataclass
    kvs[field.name] = field.default_factory()
  File "C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\tfaip\util\versioning.py", line 30, in get_commit_hash
    h = subprocess.check_output(['git', 'rev-parse', 'HEAD'], text=True, cwd=this_dir).strip()
  File "C:\Users\User\Anaconda3\envs\Logo\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\User\Anaconda3\envs\Logo\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\User\Anaconda3\envs\Logo\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\User\Anaconda3\envs\Logo\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by ChWick** [comment]
thanks for reporting this! Unfortunately, this bug occurs in a dependency, and might need some time to become fixed. In the meantime please open the file (in an editor such as notepad++):
`C:\Users\User\Anaconda3\envs\Logo\lib\site-packages\tfaip\util\versioning.py` and change line 33 from
```
except subprocess.CalledProcessError:
```
to
```
except (subprocess.CalledProcessError, FileNoteFoundError):
```

I expect that this should fix your issue for now

**Comment by andbue** [comment]
For some mysterious reason tfaip (the framework calamari 2 is based on) checks if the current directory is a git repo. To do this, the git binary needs to be installed in the current path.

**Comment by ChWick** [comment]
@andbue The commit hash will be stored alongside a model during training. This facilitates reproducibility because you can trace exactly with which code the model was trained.

**Comment by LauraLittt** [comment]
Thank you everybody! @ChWick your solutions helps! Thank you very much!


On a side note, do you know where are the output files located. I am sorry really new to coding so i am still very confused hahah
