### ISSUE TITLE
Error occured when using the last version of Calamari OCR

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#221]
Hello!
@ChWick 
I was installed calamari-ocr-2.0.2 with a python virtual environment(virtualenv --python=/usr/bin/python3 venv; !source venv/bin/activate) with a python version='3.7.10'
But when I try to test this ocr using  this command "calamari-predict  --checkpoint  /content/drive/MyDrive/model/1.ckpt  --files  *.png --output_dir /content/drive/result/"
It returns this error:

`2021-04-05 04:45:07.716823: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
INFO     2021-04-05 04:45:08,892       tfaip.base.device_config: Setting up device config DeviceConfigParams(gpus=[], gpu_auto_tune=False, gpu_memory=None, soft_device_placement=True, dist_strategy=<DistributionStrategy.Default: 'default'>)
2021-04-05 04:45:08.893153: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-04-05 04:45:08.956801: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-05 04:45:08.957375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2021-04-05 04:45:08.957417: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-04-05 04:45:09.199724: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-04-05 04:45:09.321720: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-04-05 04:45:09.372462: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-04-05 04:45:09.621559: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-04-05 04:45:09.675940: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-04-05 04:45:10.192756: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-04-05 04:45:10.192912: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-05 04:45:10.193565: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-05 04:45:10.194088: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
INFO     2021-04-05 04:45:10,387 calamari_ocr.ocr.savedmodel.sa: Upgrading from version 2
CRITICAL 2021-04-05 04:45:11,564             tfaip.util.logging: Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/calamari-predict", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/predict.py", line 196, in main
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/predict.py", line 98, in run
    predictor = MultiPredictor.from_paths(checkpoints=args.checkpoint, voter_params=voter_params, predictor_params=PredictorParams(silent=True, progress_bar=not args.no_progress_bars))
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/predict/predictor.py", line 48, in from_paths
    checkpoints = [SavedCalamariModel(ckpt, auto_update=auto_update_checkpoints) for ckpt in checkpoints]
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/predict/predictor.py", line 48, in <listcomp>
    checkpoints = [SavedCalamariModel(ckpt, auto_update=auto_update_checkpoints) for ckpt in checkpoints]
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/savedmodel/saved_model.py", line 32, in __init__
    self.update_checkpoint()
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/savedmodel/saved_model.py", line 53, in update_checkpoint
    self._single_upgrade()
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/savedmodel/saved_model.py", line 71, in _single_upgrade
    self.dict = migrate(self.dict)
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/savedmodel/migrations/version2to3.py", line 207, in migrate
    convert_text_processor(text_preprocessor)
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/savedmodel/migrations/version2to3.py", line 166, in convert_text_processor
    recurse_convert(proc)
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/savedmodel/migrations/version2to3.py", line 148, in recurse_convert
    recurse_convert(c)
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/savedmodel/migrations/version2to3.py", line 155, in recurse_convert
    flat.append(text_processor("BidiTextProcessor", args={'bidi_direction': conv[p.get('bidiDirection', 0)]}))
TypeError: list indices must be integers or slices, not str`
Please can you help me resolve this problem.
Thanks in advance for you

**Comment by andbue** [comment]
Same here, happens when upgrading a BIDI-model. The lines at [https://github.com/Calamari-OCR/calamari/blob/fc2d612b7a1199d9ebede250655d22409ccd2a2c/calamari_ocr/ocr/savedmodel/migrations/version2to3.py#L153](https://github.com/Calamari-OCR/calamari/blob/fc2d612b7a1199d9ebede250655d22409ccd2a2c/calamari_ocr/ocr/savedmodel/migrations/version2to3.py#L153)
should probably be something like
``` python
elif t == 'BIDI_NORMALIZER':
    conv = {'BIDI_AUTO': None, 'BIDI_LTR': 'L', 'BIDI_RTL': 'R'}
    flat.append(text_processor("BidiTextProcessor", args={'bidi_direction': conv[p.get('bidiDirection', 'BIDI_AUTO')]}))
```
