### ISSUE TITLE
TypeError: metaclass conflict (problem with tfaip?)

### ISSUE THREAD

**Issue by alexander-winkler** [Calamari-OCR/calamari#246]
Hello! 

I'm not sure if I'm missing something, but as there has already been a problem with tfaip (#205), I wanted to point out an issue I'm struggling with when installing the latest version of calamari.

Here my output. Any hints welcome, the hack provided in the above-mentioned issue does not work.

```
 user@user:~/virtualenvs/calamari_2-1-1/calamari(master)$ calamari-train --version
Traceback (most recent call last):
  File "/home/user/virtualenvs/calamari_2-1-1/bin/calamari-train", line 33, in <module>
    sys.exit(load_entry_point('calamari-ocr==2.1.1', 'console_scripts', 'calamari-train')())
  File "/home/user/virtualenvs/calamari_2-1-1/bin/calamari-train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/user/virtualenvs/calamari_2-1-1/lib/python3.6/site-packages/importlib_metadata-4.0.1-py3.6.egg/importlib_metadata/__init__.py", line 166, in load
    module = import_module(match.group('module'))
  File "/home/user/virtualenvs/calamari_2-1-1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/virtualenvs/calamari_2-1-1/lib/python3.6/site-packages/calamari_ocr-2.1.1-py3.6.egg/calamari_ocr/scripts/train.py", line 5, in <module>
    from tfaip.util.logging import logger, WriteToLogFile
  File "/home/user/virtualenvs/calamari_2-1-1/lib/python3.6/site-packages/tfaip-1.1.1-py3.6.egg/tfaip/__init__.py", line 37, in <module>
    from tfaip.scenario.scenariobaseparams import ScenarioBaseParams
  File "/home/user/virtualenvs/calamari_2-1-1/lib/python3.6/site-packages/tfaip-1.1.1-py3.6.egg/tfaip/scenario/scenariobaseparams.py", line 48, in <module>
    class ScenarioBaseParams(Generic[TDataParams, TModelParams], ABC, metaclass=ScenarioBaseParamsMeta):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by andbue** [comment]
Hi Alexander, I could not reproduce the error on both py3.8 and py3.6. Did you start with a clean virtualenv and just `pip install calamari-ocr`?

**Comment by ChWick** [comment]
@andbue Interesting that it is working with python 3.6 at all, since calamari 2.x uses various python 3.7 features... Maybe this explains the error @alexander-winkler, i.e. use python>=3.7?

**Comment by alexander-winkler** [comment]
I've had to install various versions of calamari (for use with OCR4all) on various systems (using virtualenvs) and I have to admit that it feels a bit like herding cats as it takes me a great deal of trial and error to get python-version + requirements right. The suggestion in #179 (add version ranges in `requirements.txt`) could probably make things easier and one might also add some indications with regard to OCR4all compatibility.

**Comment by andbue** [comment]
The last one is a bug in pagexml_dataset/dataset.py (in cutout, dimension in line 250 and 251 have to be increased by 1) that was fixed with the 2.0 update. @ChWick: should we fix bugs in earlier version?

The grpcio compilation did throw some errors in my tests as well. I was able to install it from the wheel, however. -> `pip install wheel` before installing calamari-ocr.

**Comment by ChWick** [comment]
The bug-fix can be integrated in the calamar/1.0 branch, however I generally do not want to maintain old releases since this would consume much more time...

**Comment by alexander-winkler** [comment]
Thanks, @andbue ! @ChWick , I fully understand. The only reason why I stick in part to the previous version is the compatibility with OCR4all.

**Comment by andbue** [comment]
I've updated calamari/1.0. @alexander-winkler, could you please verify that the new version works with your PageXML data? You should be able to install it with `pip install git+https://github.com/Calamari-OCR/calamari.git@calamari/1.0`.

**Comment by alexander-winkler** [comment]
installs smoothly apart from 3 requirements that I had to install manually. 

```
ERROR: tensorflow 2.5.0 has requirement h5py~=3.1.0, but you'll have h5py 3.2.1 which is incompatible.
ERROR: tensorflow 2.5.0 has requirement numpy~=1.19.2, but you'll have numpy 1.20.3 which is incompatible.
ERROR: tensorflow 2.5.0 has requirement six~=1.15.0, but you'll have six 1.16.0 which is incompatible.
```

Now I'm struggling with another problem which sound familiar but which I haven't looked into yet:

```
Traceback (most recent call last):  
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/scripts/train.py", line 371, in <module>
    main()                                                                                                 
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/scripts/train.py", line 367, in main
    run(args)                     
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/scripts/train.py", line 359, in run     
    progress_bar=not args.no_progress_bars
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/ocr/trainer.py", line 197, in train 
    self._run_train(train_net, train_start_time, progress_bar, self.dataset, self.validation_dataset, training_callback)
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/ocr/trainer.py", line 213, in _run_train
    train_net.train(train_dataset, val_dataset, checkpoint_params, self.txt_postproc, progress_bar, training_callback)
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py", line 320, in train
    predict_func = K.function({t.op.name: t for t in [self.input_data, self.input_length, self.input_params, self.targets, self.targets_length]}, [self.cer, self.sparse_targets, self.sparse_decoded])
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py", line 320, in <dictcomp>
    predict_func = K.function({t.op.name: t for t in [self.input_data, self.input_length, self.input_params, self.targets, self.targets_length]}, [self.cer, self.sparse_targets, self.sparse_decoded])
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/tensorflow/python/keras/engine/keras_tensor.py", line 232, in op                     
    raise TypeError('Keras symbolic inputs/outputs do not '                                                                                                                                            
TypeError: Keras symbolic inputs/outputs do not implement `op`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambd
a layer in the Functional Model.                                                                                                                                                                       
multiprocessing.pool.RemoteTraceback:                                                                                                   
"""                                                        
Traceback (most recent call last):                                                                                                                                                                                                            
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))       
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/ocr/cross_fold_trainer.py", line 29, in train_individual_model
    ], args.get("run", None), {"threads": args.get('num_threads', -1)}), verbose=args.get("verbose", False)):
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/utils/multiprocessing.py", line 87, in run
    raise Exception("Error: Process finished with code {}".format(process.returncode))
Exception: Error: Process finished with code 1                                                                                                     
"""                                                                                                          
                                                                                                                               
The above exception was the direct cause of the following exception:                  
                                              
Traceback (most recent call last):
  File "/home/user/virtualenvs/calamari_1-0/bin/calamari-cross-fold-train", line 11, in <module>
    load_entry_point('calamari-ocr==1.0.5', 'console_scripts', 'calamari-cross-fold-train')()
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/scripts/cross_fold_train.py", line 80, in main
    temporary_dir=args.temporary_dir, keep_temporary_files=args.keep_temporary_files,
  File "/home/user/virtualenvs/calamari_1-0/lib/python3.7/site-packages/calamari_ocr/ocr/cross_fold_trainer.py", line 156, in run
    pool.map_async(train_individual_model, run_args).get()                                   
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get                                                              
    raise self._value                                                                
Exception: Error: Process finished with code 1```

**Comment by ChWick** [comment]
calamari 1 requires tensorflow 2.1 (maximum 2.2)

**Comment by alexander-winkler** [comment]
Now,
