### ISSUE TITLE
Unknown layer with name: maxpool

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#293]
Hello!
@ChWick @andbue 
I try a train from scratch using the option --network. I put a maxpool=2*2
it returns me this message 
`CRITICAL 2021-11-17 09:12:48,889             tfaip.util.logging: Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/calamari-train", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/train.py", line 16, in run
    main(parse_args())
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/train.py", line 39, in parse_args
    return parser.parse_args(args).trainer
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/main_parser.py", line 89, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/main_parser.py", line 60, in parse_known_args
    namespace, args = self._data_class_parser.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/dataclass_parser.py", line 548, in parse_known_args
    setattr(namespace, name, self._tree_to_data_class(v))
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/dataclass_parser.py", line 364, in _tree_to_data_class
    dc = node.parsed_type(**param_values)
  File "<string>", line 42, in __init__
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/training/params.py", line 76, in __post_init__
    self.scenario.model.layers = graph_params_from_definition_string(self.network)
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/training/params.py", line 197, in graph_params_from_definition_string
    raise Exception("Unknown layer with name: {}".format(label))
Exception: Unknown layer with name: maxpool`
Please can your help me solving this error!
Thanks in advance

**Comment by andbue** [comment]
Have a look at the docs: https://calamari-ocr.readthedocs.io/en/latest/doc.command-line-usage.html#network-architecture
The syntax would be "pool=2x2".

**Comment by Tailor2019** [comment]
Thanks a lot!
