### ISSUE TITLE
Error when I launch the train from scratch 

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#295]
Hello!
@ChWick @andbue 
Please how can I solve this error?
`2021-11-23 03:58:16.181770: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
/usr/local/lib/python3.7/dist-packages/tensorflow_addons/utils/ensure_tf_install.py:67: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.5.0 and strictly below 2.8.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.4.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
CRITICAL 2021-11-23 03:59:08,404             tfaip.util.logging: Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/calamari-train", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/train.py", line 16, in run
    main(parse_args())
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/train.py", line 39, in parse_args
    return parser.parse_args(args).trainer
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/main_parser.py", line 89, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/main_parser.py", line 60, in parse_known_args
    namespace, args = self._data_class_parser.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/dataclass_parser.py", line 548, in parse_known_args
    setattr(namespace, name, self._tree_to_data_class(v))
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/dataclass_parser.py", line 364, in _tree_to_data_class
    dc = node.parsed_type(**param_values)
  File "<string>", line 42, in __init__
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/training/params.py", line 76, in __post_init__
    self.scenario.model.layers = graph_params_from_definition_string(self.network)
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/training/params.py", line 95, in graph_params_from_definition_string
    label, value = tuple(param.split("="))
ValueError: too many values to unpack (expected 2)` 
Thanks in advance!

**Comment by andbue** [comment]
It looks like your model definition string had some error in it.

**Comment by Tailor2019** [comment]
Hello!
thanks @andbue 
this colab notebook
 https://github.com/andbue/calamari_demo/blob/main/calamari_train.ipynb
does not open.
Please how can I open it beause I need it ?
Thanks in advance!

**Comment by andbue** [comment]
Please open issues regarding the demo notebook in the calamari_demo repo.
https://colab.research.google.com/github/andbue/calamari_demo/blob/main/calamari_train.ipynb opens fine when I'm testing it. You can also open it locally with jupyter notebook.
