### ISSUE TITLE
Question regarding a code block inside text_processing/text_processor.py

### ISSUE THREAD

**Issue by YongGuCheng** [Calamari-OCR/calamari#58]
Thank you for providing us with such a nice open-source OCR tool. 
I am analyzing the codes of Calamari-OCR. I have a question regarding a code block inside text_processing/text_processor.py.
In class MultiTextProcessor(TextProcessor):
```python
def _apply_single(self, txt):
    for proc in self.sub_processors:
        txt = proc._apply_single(txt)
    return txt
```
This for loop is very difficult to understand. What does this block of codes do? Can we skip this for loop?
Looking forward to your reply.

**Comment by ChWick** [comment]
A `MultiTextProcessor` is simply a `TextProcessor` that calls multiple other `TextProcessor`s in sequence. E. g. the `DefaultTextPreprocessor` is a `MultiTextProcessor` and will call:
* `BidiTextProcessor` to unify bidirectional text
* `StripTextPreprocessor` to strip whitespace at the beginning and ending of a string
* `TextNormalizer` to normalize utf-8 ligatures, etc.
* `TextRegularizer` to apply replacements of similar looking, or equal utf-8 characters (mostly quotes)

**Comment by hala3** [comment]
hello, i have this problem when i run 

D:\>calamari-train --help
Traceback (most recent call last):
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\conda\conda\envs\calamari\Scripts\calamari-train.exe\__main__.py", line 5, in <module>
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\scripts\train.py", line 5, in <module>
    from calamari_ocr.ocr.datasets import create_dataset, DataSetType, DataSetMode
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\ocr\__init__.py", line 2, in <module>
    from calamari_ocr.ocr.codec import Codec
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\ocr\codec.py", line 2, in <module>
    from calamari_ocr.ocr.datasets import InputDataset
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\ocr\datasets\__init__.py", line 6, in <module>
    from .input_dataset import InputDataset, RawInputDataset
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\ocr\datasets\input_dataset.py", line 26, in <module>
    class InputDataset:
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\ocr\datasets\input_dataset.py", line 83, in InputDataset
    def generator(self) -> Generator[Tuple[np.array, List[str], Any], None, None]:
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\typing.py", line 693, in __getitem__
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\typing.py", line 693, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\typing.py", line 299, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Tuple[t0, t1, ...]: each t must be a type. Got <built-in function array>.

(calamari) D:\>calamari-train --help
Traceback (most recent call last):
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\conda\conda\envs\calamari\Scripts\calamari-train.exe\__main__.py", line 5, in <module>
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\scripts\train.py", line 5, in <module>
    from calamari_ocr.ocr.datasets import create_dataset, DataSetType, DataSetMode
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\ocr\__init__.py", line 2, in <module>
    from calamari_ocr.ocr.codec import Codec
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\ocr\codec.py", line 2, in <module>
    from calamari_ocr.ocr.datasets import InputDataset
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\ocr\datasets\__init__.py", line 6, in <module>
    from .input_dataset import InputDataset, RawInputDataset
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\ocr\datasets\input_dataset.py", line 26, in <module>
    class InputDataset:
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\site-packages\calamari_ocr\ocr\datasets\input_dataset.py", line 83, in InputDataset
    def generator(self) -> Generator[Tuple[np.array, List[str], Any], None, None]:
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\typing.py", line 693, in __getitem__
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\typing.py", line 693, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "c:\users\user\appdata\local\conda\conda\envs\calamari\lib\typing.py", line 299, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Tuple[t0, t1, ...]: each t must be a type. Got <built-in function array>.


can you help me please

**Comment by ChWick** [comment]
@hala3 Which Python version are you using? Please consider to open an new issue (!) instead of posting to an other also unrelated issue...
