### ISSUE TITLE
Training crashes when checkpoint is saved

### ISSUE THREAD

**Issue by dhruvspatel** [Calamari-OCR/calamari#70]
Error Description: The training crashes when it comes to the point where it has to store the model weights to the checkpoint. I reviewed issues #38 and #40 but they didn't work out for me. Here is the complete description of my software stack and error:

OS: Windows 10
Python: 3.6
CUDA / cuDNN: 9.0 / 7.3.1
Training on CPU/GPU (tried both, facing the same error)
Tensorflow version: 1.12.0
Calamari version: 0.2.4
Installed via 'conda env create -f environment_master_gpu.yml'

Full Command: 

calamari-train --files \calamari_training_data\*.png --output_dir ...\Checkpoints\c7 --checkpoint_frequency=1000 --weights ...\Calamari\antiqua_modern\4.ckpt --whitelist ...Calamari\whitelist.txt  

Complete Error Stack:

Traceback (most recent call last):
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dsureshkumar\Anaconda3\envs\calamari_gpu\Scripts\calamari-train.exe\__main__.py", line 9, in <module>
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\site-packages\calamari_ocr\scripts\train.py", line 310, in main
    run(args)
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\site-packages\calamari_ocr\scripts\train.py", line 302, in run
    progress_bar=not args.no_progress_bars
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\site-packages\calamari_ocr\ocr\trainer.py", line 175, in train
    self._run_train(train_net, test_net, codec, train_start_time, progress_bar)
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\site-packages\calamari_ocr\ocr\trainer.py", line 319, in _run_train
    last_checkpoint = make_checkpoint(checkpoint_params.output_dir, checkpoint_params.output_model_prefix)
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\site-packages\calamari_ocr\ocr\trainer.py", line 264, in make_checkpoint
    f.write(json_format.MessageToJson(checkpoint_params))
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\site-packages\google\protobuf\json_format.py", line 127, in MessageToJson
    return printer.ToJsonString(message, indent, sort_keys)
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\site-packages\google\protobuf\json_format.py", line 178, in ToJsonString
    return json.dumps(js, indent=indent, sort_keys=sort_keys)
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\json\encoder.py", line 437, in _iterencode
    o = _default(o)
  File "c:\users\dsureshkumar\anaconda3\envs\calamari_gpu\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'float32' is not JSON serializable
2019-02-28 10:07:34.188243: W tensorflow/core/kernels/data/generator_dataset_op.cc:78] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_INT64], token="pyfunc_2"](arg0)]]

**Comment by ChWick** [comment]
I was not able to reproduce this crash on Linux with anaconda, however (luckily), I was able to reproduce the crash on windows.
I made a fix on the dev branch. Can you please confirm that the fix resolves your issue, then i will push it into the master branch (use `environment_dev_gpu.yml`)

**Comment by dhruvspatel** [comment]
Yes! It is working on both CPU and GPU now. **environment_dev_gpu.yml** installs the CPU version of Tensorflow by default so I checked on that first, it worked. Later, I uninstalled that and installed **tensorflow-gpu==1.12** and that worked too! Checkpoints are being saved after the desired number of iterations and the model is training. Thank you for your help!

**Correction:
cuDNN: 7.4.1

**Comment by ChWick** [comment]
Thanks!
