### ISSUE TITLE
Cannon kill train with ctrl-C

### ISSUE THREAD

**Issue by wosiu** [Calamari-OCR/calamari#77]
Using 0.3.0 
BTW I love the new feature with async loading data in the "on the fly" mode. :) 
However I guess it introduced a minor error.
I tried several "Ctrl-C" to kill training, without a luck:
```
^CProcess ForkProcess-5:
Process SpawnProcess-22:
Process ForkProcess-6:
Process ForkProcess-7:
Process ForkProcess-8:
Process ForkProcess-3:
Process ForkProcess-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 64, in run
    out = self.apply_single(*data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 76, in apply_single
    line, params = self.params.data_processor.apply([line], 1, False)[0]
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 19, in apply
    processes=processes, progress_bar=progress_bar, max_tasks_per_child=max_tasks_per_child)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/utils/multiprocessing.py", line 30, in parallel_map
    out = list(map(f, d))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 50, in _apply_single
    data, params = proc._apply_single(data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 50, in _apply_single
    data, params = proc._apply_single(data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 15, in _apply_single
    out, params = self.normalize(data, cval=np.amax(data))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 63, in normalize
    dewarped = self.dewarp(img, cval=cval, dtype=dtype)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 49, in dewarp
    dewarped = [padded[center[i] - r:center[i]+r, i] for i in range(w)]
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 49, in <listcomp>
    dewarped = [padded[center[i] - r:center[i]+r, i] for i in range(w)]
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 63, in run
    data = self.input_queue.get()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 63, in run
    data = self.input_queue.get()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 29, in run
    data.append(self.input_queue.get())
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 63, in run
    data = self.input_queue.get()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 64, in run
    out = self.apply_single(*data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 76, in apply_single
    line, params = self.params.data_processor.apply([line], 1, False)[0]
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 19, in apply
    processes=processes, progress_bar=progress_bar, max_tasks_per_child=max_tasks_per_child)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/utils/multiprocessing.py", line 30, in parallel_map
    out = list(map(f, d))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 50, in _apply_single
    data, params = proc._apply_single(data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 50, in _apply_single
    data, params = proc._apply_single(data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 15, in _apply_single
    out, params = self.normalize(data, cval=np.amax(data))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 63, in normalize
    dewarped = self.dewarp(img, cval=cval, dtype=dtype)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 49, in dewarp
    dewarped = [padded[center[i] - r:center[i]+r, i] for i in range(w)]
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 49, in <listcomp>
    dewarped = [padded[center[i] - r:center[i]+r, i] for i in range(w)]
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 63, in run
    data = self.input_queue.get()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Process ForkProcess-4:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 64, in run
    out = self.apply_single(*data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 76, in apply_single
    line, params = self.params.data_processor.apply([line], 1, False)[0]
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 19, in apply
    processes=processes, progress_bar=progress_bar, max_tasks_per_child=max_tasks_per_child)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/utils/multiprocessing.py", line 30, in parallel_map
    out = list(map(f, d))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 50, in _apply_single
    data, params = proc._apply_single(data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 50, in _apply_single
    data, params = proc._apply_single(data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 15, in _apply_single
    out, params = self.normalize(data, cval=np.amax(data))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 63, in normalize
    dewarped = self.dewarp(img, cval=cval, dtype=dtype)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 42, in dewarp
    center, r = self.measure(temp)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 23, in measure
    smoothed = filters.gaussian_filter(line, (h * 0.5, h * self.smoothness), mode='constant')
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 286, in gaussian_filter
    mode, cval, truncate)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 204, in gaussian_filter1d
    return correlate1d(input, weights, axis, output, mode, cval, 0)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 92, in correlate1d
    origin)
KeyboardInterrupt
Process ForkProcess-1:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 64, in run
    out = self.apply_single(*data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/input_dataset.py", line 76, in apply_single
    line, params = self.params.data_processor.apply([line], 1, False)[0]
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 19, in apply
    processes=processes, progress_bar=progress_bar, max_tasks_per_child=max_tasks_per_child)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/utils/multiprocessing.py", line 30, in parallel_map
    out = list(map(f, d))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 50, in _apply_single
    data, params = proc._apply_single(data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 50, in _apply_single
    data, params = proc._apply_single(data)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 15, in _apply_single
    out, params = self.normalize(data, cval=np.amax(data))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 63, in normalize
    dewarped = self.dewarp(img, cval=cval, dtype=dtype)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 42, in dewarp
    center, r = self.measure(temp)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/data_processing/center_normalizer.py", line 23, in measure
    smoothed = filters.gaussian_filter(line, (h * 0.5, h * self.smoothness), mode='constant')
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 286, in gaussian_filter
    mode, cval, truncate)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 204, in gaussian_filter1d
    return correlate1d(input, weights, axis, output, mode, cval, 0)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 92, in correlate1d
    origin)
KeyboardInterrupt
^CProcess SpawnProcess-21:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/calamari_ocr/ocr/datasets/dataset.py", line 44, in run
    self.output_queue.put((global_index, sample_idx, line, text))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/queues.py", line 285, in put
    if not self._sem.acquire(block, timeout):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/util.py", line 322, in _exit_function
    _run_finalizers()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/queues.py", line 191, in _finalize_join
    thread.join()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
 ^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

And when I finally killed it with kill -9, then in the logs:
```
/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 40 leaked semaphores to clean up at shutdown
  len(cache))
```

**Comment by thak123** [comment]
it keeps the program in  GPU memory if u press ctrl+c

**Comment by ChWick** [comment]
@wosiu @thak123 Thanks for the report! I think I got it fixed, however due to multiprocessing I can not be 'sure' if there is another deadlock at some point. I'm running some further tests, then I will push the fix in the master branch and on pypi.
