### ISSUE TITLE
Error occured when I trained new model.

### ISSUE THREAD

**Issue by a41888936** [Calamari-OCR/calamari#9]
I tried to train new model using 

> calamari-train --files your_images.*.png

During saving ckpt.json, I got some error like this.

```
Storing checkpoint to '/home/hclee/calamari/model_00001000.ckpt'
Traceback (most recent call last):
  File "/home/hclee/anaconda3/envs/calamari/bin/calamari-train", line 11, in <module>
    load_entry_point('calamari-ocr==0.1.8', 'console_scripts', 'calamari-train')()
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/site-packages/calamari_ocr-0.1.8-py3.5.egg/calamari_ocr/scripts/train.py", line 233, in main
    run(args)
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/site-packages/calamari_ocr-0.1.8-py3.5.egg/calamari_ocr/scripts/train.py", line 226, in run
    trainer.train(progress_bar=not args.no_progress_bars)
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/site-packages/calamari_ocr-0.1.8-py3.5.egg/calamari_ocr/ocr/trainer.py", line 259, in train
    last_checkpoint = make_checkpoint(checkpoint_params.output_dir, checkpoint_params.output_model_prefix)
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/site-packages/calamari_ocr-0.1.8-py3.5.egg/calamari_ocr/ocr/trainer.py", line 210, in make_checkpoint
    f.write(json_format.MessageToJson(checkpoint_params))
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/site-packages/protobuf-3.6.0-py3.5.egg/google/protobuf/json_format.py", line 127, in MessageToJson
    return printer.ToJsonString(message, indent, sort_keys)
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/site-packages/protobuf-3.6.0-py3.5.egg/google/protobuf/json_format.py", line 178, in ToJsonString
    return json.dumps(js, indent=indent, sort_keys=sort_keys)
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/hclee/anaconda3/envs/calamari/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
```

How should I fix this?

**Comment by a41888936** [comment]
I got it. It's because python version... I upgrade python 3.6 and It works.
